### PR TITLE
Roles is a property, not a method

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by bdero** [comment]
Is this valid for the current version on pypi, or will it only work after the next release?

**Comment by carsongee** [comment]
Good question, but it is how our current release works: https://github.com/mitodl/pylti/blob/release/pylti/flask.py#L144

**Comment by bdero** [comment]
Ah, great :information_desk_person:

**Comment by carsongee** [comment]
I like :information_desk_person: lol

**Pull request merged**
