### PR TITLE
Correct argument is role

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by pdpinch** [comment]
Oops. How should we verify this?

**Comment by carsongee** [comment]
this branch is running on our test LTI, so https://lms-staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/c8ce33eb31e3477a817baaa25f401926/21fde1601bec4b3cab1f7363ccbc7e5b/ as admin make sure you can see the staff page, and as student view, make sure you can't

**Comment by bdero** [comment]
My question in #25 also applies to this PR.

**Comment by carsongee** [comment]
True since 0.1.3 which is how it was originally coded: https://github.com/mitodl/pylti/commit/841e6f6f0f558308a8003c84feb0bdf57bc72d19

**Comment by carsongee** [comment]
https://github.com/mitodl/pylti/commit/841e6f6f0f558308a8003c84feb0bdf57bc72d19#diff-9d3b4f907666c7df88d8b01ea790b1c4R88

**Comment by bdero** [comment]
Alrighty, looks good :smiling_imp:

**Pull request merged**
